version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - pg

  pg:
    container_name: pg
    image: postgres:14-alpine3.18
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: docker/migrator/Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg